Improve compatibility
* Add Windows support. Resolves #1

* Use sublime.set_timeout instead of a background thread, to avoid

      RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

  when trying to access settings on Sublime 2 on Windows and perhaps some other platforms too.